Wide and Deep mimarisi girdilerin tamamını ya da bir kısmını doğrudan çıktı katmanına bağlar. Bu mimari, sinir ağının hem derin örüntüleri hem de basit kuralları öğrenmesini sağlar

### `Burada Wade ve Deep river larına verilecek değişken sayısı aynı [1:]`

input_ = keras.layer.Input(shape=X_train.shape[1:])

hidden1 = keras.layer.Dense(30, activation="relu")(input_)

hidden2 = keras.layer.Dense(30, activation="relu")(hidden1)

concat = keras.layer.Concatenate()([input_, hidden1])

output = keras.layers.Dense(1)(concat)

model = keras.Model(input=[input_], output=[output])

### `Burada Wade ve Deep river larına verilercek değişken sayısı farklı`

+   1.jpeg

input_A = keras.layer.Input(shape=[5], name="wade_input")

input_B = keras.layer.Input(shape=[6], name="deep_input")

hidden1 = keras.layer.Dense(30, activation="relu")(input_B)

hidden2 = keras.layer.Dense(30, activation="relu")(hidden1)

concat = keras.layer.concatenate([input_A, hidden2])

output = keras.layer.Dense(1, name="output")(concat)

model = keras.Model(input=[input_A, input_B], outputs=[output])


## For Example

In [ ]:
import pandas as pd
import numpy as np

np.random.random(42)

data = {
    'Yas': np.random.randint(18, 60, 20),           # 1. Değişken
    'Yillik_Gelir': np.random.randint(30000, 150000, 20), # 2. Değişken
    'Sitede_Gecen_Sure_Dk': np.random.randint(1, 45, 20), # 3. Değişken
    'Toplam_Harcama': np.random.uniform(100.0, 5000.0, 20).round(2), # 4. Değişken

    'Meslek': np.random.choice(['Mühendis', 'Doktor', 'Öğrenci', 'Sanatçı'], 20), # 5. Değişken
    'Sehir': np.random.choice(['İstanbul', 'Ankara', 'İzmir', 'Bursa'], 20),      # 6. Değişken
    'Cihaz_Tipi': np.random.choice(['Mobil', 'Masaüstü', 'Tablet'], 20),          # 7. Değişken

    # 1: Tıkladı, 0: Tıklamadı
    'Tiklama_Durumu': np.random.randint(0, 2, 20)   # 8. Değişken (Target)
}

df = pd.DataFrame(data)

df.head() 

20

### Data Preposition

In [2]:
deep_features = df[["Yas", "Yillik_Gelir", "Sitede_Gecen_Sure_Dk", "Toplam_Harcama"]].values
wide_features = pd.get_dummies(df[["Meslek","Sehir","Cihaz_Tipi"]]).values
y_target = df[["Tiklama_Durumu"]].values

# Modelimizi oluştururken modele girecek input shape sayısını belirlemek için kendi modelimi referans alıyoruz. Yani bu modeli kullanacak olanlar
# 4 değişkenlerini deep inputundan, 11 değişkenlerini de wide inputundan sokacaklar gibi...
col_wide_features = wide_features.shape[1] # Sütun sayısı 11
col_deep_features = deep_features.shape[1] # Sütun sayısı 4

### Making model

In [ ]:
# MODEL OLUŞTURMA AŞAMASI

# !pip install scikit-learn
# !pip install tensorflow==2.20.0 

from tensorflow.keras import Input, layers, Model
import keras

Input_wide = keras.layers.Input(shape=(col_wide_features,), name="wide_input") # Modelin memorize edeceği değşler.
Input_deep = keras.layers.Input(shape=(col_deep_features,), name="deep_input") # Modelin generalize edeceği değşler.
hidden1 = keras.layers.Dense(30, activation="relu")(Input_deep)
hidden2 = keras.layers.Dense(20, activation="relu")(hidden1)
concat = keras.layers.concatenate([Input_wide, hidden2])
output = keras.layers.Dense(1, activation="sigmoid", name="output")(concat)

model = keras.Model(inputs=[Input_wide, Input_deep], outputs=[output]) 

### Building Optimizer,loss,metrics that we maked model 

In [60]:
from tensorflow import optimizers
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

model.compile(loss="binary_crossentropy", optimizer=keras.optimizers.SGD(learning_rate=1e-3), metrics=["accuracy", 
                                                                                                       keras.metrics.Precision(name='precision'),
                                                                                                       keras.metrics.Recall(name='recall'),
                                                                                                       keras.metrics.F1Score(name='F1')]) 

## Train Test Validation

In [61]:
train_size = int(len(df)*0.80)

X_train_wide = wide_features[:train_size] 
X_test_wide = wide_features[train_size:]

X_train_deep = deep_features[:train_size]
X_test_deep = deep_features[train_size:]

y_train = y_target[:train_size]
y_test  = y_target[train_size:] 

In [62]:
history = model.fit((X_train_wide, X_train_deep), y_train, epochs=10) 

Epoch 1/10


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 692ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6410 - precision: 0.5556 - recall: 0.8333
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6409 - precision: 0.5556 - recall: 0.8333
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6409 - precision: 0.5556 - recall: 0.8333
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6408 - precision: 0.5556 - recall: 0.8333
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6408 - precision: 0.5556 - recall: 0.8333
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6407 - precision: 0.5556 - recall: 0.8333
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - F1: 0.5455 - accuracy: 0.6875 - loss: 0.6406 - precision: 0.5556 - recall: 0.8333
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - F1: 0.5455 - accuracy: 0.687

In [63]:
X_new_wide, X_new_deep = X_test_wide, X_test_deep

y_pred_prob = model.predict([X_new_wide, X_new_deep])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


In [64]:
y_pred_class = (y_pred_prob > 0.5).astype("int32")
y_pred_class, y_test 

(array([[0],
        [1],
        [1],
        [1]], dtype=int32),
 array([[0],
        [1],
        [0],
        [0]]))

### `Comparison of the two outputs (output, aux_output)`

Burada amacımız Memorizing(Ezberlemeye) bağlı kalmadan genelleme ağının altta yatan kısmının kendi başına yararlı bir şey öğrenmesini garanti etmek için sinir ağı mmimarisine bu seneryoda olduğu gibi bazı yardımcı çıktılar eklemek isteyebiliriz.


+   2.jpeg

output = keras.layers.Dense(1, name="main_output")(concat)

aux_output = keras.layers.Dense(1, name="aux_output")(hidden2)

model = keras.Model(inputs=[input_A, input_B], outputs=[output, aux_output])


In [98]:
df.head()

Yas  Yillik_Gelir  Sitede_Gecen_Sure_Dk  Toplam_Harcama    Meslek   Sehir  \
0   32         81816                    16          602.00    Doktor  Ankara   
1   43         76914                    17         3290.37    Doktor   Bursa   
2   40         41123                    20         4672.16  Mühendis   Bursa   
3   52         30071                     7         1298.80   Sanatçı  Ankara   
4   36        132075                    30         4008.44   Öğrenci   Bursa   

  Cihaz_Tipi  Tiklama_Durumu  
0     Tablet               0  
1     Tablet               0  
2      Mobil               0  
3     Tablet               0  
4      Mobil               0

In [99]:
deep_features = df[["Yas", "Yillik_Gelir", "Sitede_Gecen_Sure_Dk", "Toplam_Harcama"]].values
wide_features = pd.get_dummies(df[["Meslek","Sehir","Cihaz_Tipi"]]).values
y_target = df[["Tiklama_Durumu"]].values

# Modelimizi oluştururken modele girecek input shape sayısını belirlemek için kendi modelimi referans alıyoruz. Yani bu modeli kullanacak olanlar
# 4 değişkenlerini deep inputundan, 11 değişkenlerini de wide inputundan sokacaklar gibi...
col_wide_features = wide_features.shape[1] # Sütun sayısı 11
col_deep_features = deep_features.shape[1] # Sütun sayısı 4

In [100]:
# MODEL OLUŞTURMA AŞAMASI

from tensorflow.keras import Input, layers, Model
import keras

Input_wide = keras.layers.Input(shape=(col_wide_features,), name="wide_input") # Modelin memorize edeceği değşler.
Input_deep = keras.layers.Input(shape=(col_deep_features,), name="deep_input") # Modelin generalize edeceği değşler.
hidden1 = keras.layers.Dense(30, activation="relu")(Input_deep)
hidden2 = keras.layers.Dense(20, activation="relu")(hidden1)
concat = keras.layers.concatenate([Input_wide, hidden2])
output = keras.layers.Dense(1, activation="sigmoid", name="output")(concat)
aux_output = keras.layers.Dense(1, activation="sigmoid", name="aux_output")(hidden2)

model2 = keras.Model(inputs=[Input_wide, Input_deep], outputs=[output, aux_output])
model = keras.Model(inputs=[Input_wide, Input_deep], outputs=[output]) 

In [101]:
model2.compile(loss=["binary_crossentropy", "binary_crossentropy"], loss_weights=[0.9, 0.1], optimizer="sgd") # Bizim için ana çıktı yardımcı çıktıdan daha 
                                                                                             # önemli olduğu için ana çıktıya daha fazla ağırlık verildi.

In [102]:
history2 = model2.fit([X_train_wide, X_train_deep], [y_train, y_train], epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 405ms/step - aux_output_loss: 6392.4292 - loss: 1935.9980 - output_loss: 1440.8391
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - aux_output_loss: 26881077248.0000 - loss: 217641992192.0000 - output_loss: 238837661696.0000
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - aux_output_loss: 0.6836 - loss: 3.6416 - output_loss: 3.9702
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - aux_output_loss: 0.6931 - loss: 0.7234 - output_loss: 0.7267
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - aux_output_loss: 0.6931 - loss: 0.7227 - output_loss: 0.7260
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - aux_output_loss: 0.6931 - loss: 0.7220 - output_loss: 0.7252
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - aux_output_loss: 0.6931 - loss: 0.7214 - output_loss: 0.7245
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - aux_output_loss: 0.6931 - loss: 0.7207 - output_loss: 0.7238
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - aux_output_

In [103]:
X_new_wide, X_new_deep = X_test_wide, X_test_deep

y_pred_main_prob, y_pred_aux_prob = model2.predict([X_new_wide, X_new_deep]) 

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 945ms/step


In [104]:
y_pred_main_class = (y_pred_main_prob > 0.5).astype("int32")
y_pred_aux_class = (y_pred_aux_prob > 0.5).astype("int32")

y_pred_main_class, y_test 
y_pred_aux_class, y_test

(array([[0],
        [0],
        [0],
        [0]], dtype=int32),
 array([[0],
        [1],
        [0],
        [0]]))

In [105]:
y_pred_main, y_pred_aux = model2.predict([X_new_wide, X_new_deep])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


In [109]:
y_pred_aux

array([[0.4994317],
       [0.4994317],
       [0.4994317],
       [0.4994317]], dtype=float32)

## Class of WideandDeepModel

In [ ]:
from tensorflow.keras import Input, layers, Model
import keras
from tensorflow import optimizers
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report


class WideAndDeepModel(keras.Model):
    
    def __init__(self, units=30, activation="relu", **kwargs):
        super().__init__(**kwargs) 
        self.hidden1 = keras.layers.Dense(units, activation=activation)
        self.hidden2 = keras.layers.Dense(units, activation=activation)
        self.main_output = keras.layers.Dense(1)
        self.aux_output = keras.layers.Dense(1)
        
    def call(self, inputs):
        input_A, input_B = inputs
        hidden1 = self.hidden1(input_B)
        hidden2 = self.hidden2(hidden1)
        concat = keras.layers.concatenate([input_A, hidden2])
        main_output = self.main_output(concat)
        aux_output = self.aux_output(hidden2)
        return main_output, aux_output    

model = WideAndDeepModel() 
model.call

## Müşteri Satın Alma Davranışı `(Örnek)`